### PR TITLE
Update all.sql

### PR DESCRIPTION
**Pull request by akshay11298**
Updated the data type of _time coulmn from varchar to datetime

### CODE REVIEW

**Comment by eldadfux** [comment]
Hey @akshay11298, Thank you for the PR and sorry for the late response. You are right the the _time filed datatype is incorrect but it actually needs to be an INT(11) and not a datetime because we are using it to store a unix time value.

Let me know if you can change it so I'll be able to approve your merge request otherwise I'll just fix it during the weekend.

Anyway, please reach out to me on our [Discord server](https://discord.gg/GSeTUeA) if you would like me to send you some cool Appwrite stickers and magnets!

**Comment by eldadfux** [comment]
Fixed it to int(11).

**Comment by eldadfux** [comment]
Feel free to contact me on our Discord server if you want to get some free Appwrite swags.

This is our Discord invite link:
https://discord.gg/GSeTUeA

**Comment by akshay11298** [comment]
Hi @eldafux, Thanks for pointing out the correction. I'm sorry, I was not able to make the change on time though. I'll try to go through the repository more thoroughly to understand it's functionality, so that I'm aware of these basic things. Cheers!

**Comment by eldadfux** [comment]
That will be great! Thank you so much for your help! 🙏🏻

**Pull request merged**
