### PR TITLE
Feat auto deploy with travis

### PR DESCRIPTION
**Pull request by lohanidamodar**

### CODE REVIEW

**Review by kodumbeats — APPROVED** [review]
:)

**Comment by lohanidamodar** [comment]
> :)

@kodumbeats can we skip the ARM in the travis?

**Comment by kodumbeats** [comment]
> > :)
> 
> @kodumbeats can we skip the ARM in the travis?

Yeah I think we can - we aren't running tests here anyway. If ARM breaks, the `deploy` step will throw an error.

**Comment by eldadfux** [comment]
Tests are failing 😧

**Comment by kodumbeats** [comment]
Restarted the last failing build, got 🟢

**Pull request merged**
